[pycodestyle]
max_line_length = 120
ignore = E501,W601

[options.entry_points]
console_scripts =
    
    cot = pyarcaws.cot:main
    iibb = pyarcaws.iibb:main
    padron = pyarcaws.padron:main
    pyemail = pyarcaws.pyemail:main
    pyfepdf = pyarcaws.pyfepdf:main
    pyi25 = pyarcaws.pyi25:main
    pyqr = pyarcaws.pyqr:main
    rece1 = pyarcaws.rece1:main
    receb1 = pyarcaws.receb1:main
    recem = pyarcaws.recem:main
    recet = pyarcaws.recet:main
    recex1 = pyarcaws.recex1:main
    rg3685 = pyarcaws.rg3685:main
    sired = pyarcaws.sired:main
    trazafito = pyarcaws.trazafito:main
    trazamed = pyarcaws.trazamed:main
    trazaprodmed = pyarcaws.trazaprodmed:main
    trazarenpre = pyarcaws.trazarenpre:main
    trazavet = pyarcaws.trazavet:main
    wdigdepfiel = pyarcaws.wdigdepfiel:main
    ws_sire = pyarcaws.ws_sire:main
    ws_sr_padron = pyarcaws.ws_sr_padron:main
    wsaa = pyarcaws.wsaa:main
    wsbfev1 = pyarcaws.wsbfev1:main
    wscdc = pyarcaws.wscdc:main
    wscoc = pyarcaws.wscoc:main
    wsct = pyarcaws.wsct:main
    wsctg = pyarcaws.wsctg:main   
    wsfecred = pyarcaws.wsfecred:main
    wsfev1 = pyarcaws.wsfev1:main
    wsfexv1 = pyarcaws.wsfexv1:main
    wslpg = pyarcaws.wslpg:main
    wslsp = pyarcaws.wslsp:main
    wsltv = pyarcaws.wsltv:main
    wslum = pyarcaws.wslum:main
    wsmtx = pyarcaws.wsmtx:main
    wsremazucar = pyarcaws.wsremazucar:main
    wsremcarne = pyarcaws.wsremcarne:main
    wsremharina = pyarcaws.wsremharina:main